### ISSUE TITLE
PostCSS Loader with Bootstrap-Vue Crashes

### ISSUE THREAD

**Issue by lfaudreejr** [lfaudreejr/generator-vuestacks#1]
Remove PostCSS Loader from Vue Build/Utils.sj

**Comment by howlingsails** [comment]
I tried all three compoents all have css issues.

`[1] [nodemon] starting `node server/bin/server.js`
[1] 2022-11-05T16:31:39.908Z app:server Listening on port 3000
[0] (node:28539) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
[0] (Use `node --trace-deprecation ...` to show where the warning was created)
[0]  21% building modules 99/138 modules 39 active ..._visions_generator/client/src/App.vue{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
 94% asset optimization ERROR  Failed to compile with 2 errors9:31:45 AM
[0]
[0]  error  in ./node_modules/bootstrap-vue/dist/bootstrap-vue.css
[0]
[0] Module build failed: Error: No PostCSS Config found in: /Users/bill.nortman/dev2/world_visions_generator/node_modules/bootstrap-vue/dist
[0]     at /Users/bill.nortman/dev2/world_visions_generator/node_modules/postcss-loader/node_modules/postcss-load-config/src/index.js:91:15
[0]
[0]  @ ./node_modules/bootstrap-vue/dist/bootstrap-vue.css 4:14-126 13:3-17:5 14:22-134
[0]  @ ./client/src/main.js
[0]  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
[0]
[0]  error  in ./node_modules/bootstrap/dist/css/bootstrap.css
[0]
[0] Module build failed: Error: No PostCSS Config found in: /Users/bill.nortman/dev2/world_visions_generator/node_modules/bootstrap/dist/css
[0]     at /Users/bill.nortman/dev2/world_visions_generator/node_modules/postcss-loader/node_modules/postcss-load-config/src/index.js:91:15
[0]
[0]  @ ./node_modules/bootstrap/dist/css/bootstrap.css 4:14-128 13:3-17:5 14:22-136
[0]  @ ./client/src/main.js
[0]  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
[0]`

**Comment by howlingsails** [comment]
Here is vuetify error

`[1] 2022-11-05T16:20:21.828Z app:server Listening on port 3000
[0] (node:27337) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
[0] (Use `node --trace-deprecation ...` to show where the warning was created)
[0]  14% building modules 36/41 modules 5 active ..._visions_generator/client/src/App.vue{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
 94% asset optimization ERROR  Failed to compile with 1 errors9:20:28 AM
[0]
[0]  error  in ./node_modules/vuetify/dist/vuetify.min.css
[0]
[0] Module build failed: Error: No PostCSS Config found in: /Users/bill.nortman/dev2/world_visions_generator/node_modules/vuetify/dist
[0]     at /Users/bill.nortman/dev2/world_visions_generator/node_modules/postcss-loader/node_modules/postcss-load-config/src/index.js:91:15
[0]
[0]  @ ./node_modules/vuetify/dist/vuetify.min.css 4:14-124 13:3-17:5 14:22-132
[0]  @ ./client/src/main.js
[0]  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js`

**Comment by howlingsails** [comment]
Per: https://stackoverflow.com/questions/49709252/no-postcss-config-found

Made a new file in the client root directory named postcss.config.js and added

module.exports = {};

**Comment by lfaudreejr** [comment]
@howlingsails Hey, thanks for the opening this issue. Unfortunately, I am no longer maintaining or going to maintain this repo. However, adding a postcss.config.js file to your project root and installing Bootstrap-Vue should correct this issue if you would like to use the scaffold.
